export enum Verdicts {
  IcpcStyle = 'ICPC-Style',
  Batch = 'Batch',
  OutputOnly = 'Output-only',
  Communication = 'Communication',
  Custom = 'Custom',
  Queued = 'Queued',
  Running = 'Running',
  Accepted = 'Accepted',
  TLE = 'TLE',
  RTE = 'RTE',
  MLE = 'MLE',
  CE = 'CE',
  Skipped = 'Skipped',
}
