version: '3'

services:
  postgres:
    container_name: 'postgres'
    image: 'postgres:14-bullseye'
    restart: always
    env_file:
      - .env
    ports:
      - '5432:5432'
    volumes:
      - ./database/postgres:/var/lib/postgresql/data/
  backend:
    container_name: 'backend'
    build:
      context: .
      dockerfile: Dockerfile.dev
    command: sh ./scripts/dev-backend.sh
    stdin_open: true
    tty: true
    depends_on:
      - postgres
    links:
      - postgres
    env_file:
      - .env
    ports:
      - '4000:4000'
    volumes:
      - .:/app/
