version: '3.3'

services:
  postgres:
    container_name: postgres
    image: postgres:14-bullseye
    restart: always
    env_file:
      - .env
    ports:
      - 5432:5432
    volumes:
      - ./web-server/database/postgres:/var/lib/postgres/data/
  backend:
    container_name: backend
    build: 
      context: ./web-server/
      dockerfile: dockerfile.backend
    command: sh scripts/backend.sh
    stdin_open: true
    tty: true
    depends_on:
      - postgres
    links:
      - postgres
    env_file:
      - .env
    ports:
      - 4000:4000
    volumes:
      - ./web-server/:/app/