version: '3.3'
 
services:
  hurado-server:
    container_name: hurado-dev
    image: noiph/hurado:latest
    working_dir: /app
    command: npm run dev
    environment:
      - IS_UNDER_DOCKER=true
    env_file:
      - .env
    ports:
      - 10000:10000
    restart: always
    depends_on:
      - hurado-postgres
    links:
      - hurado-postgres
    volumes:
      - ./:/app/
  hurado-judge:
    container_name: hurado-judge
    image: noiph/hurado:latest
    privileged: true
    working_dir: /app
    command: npm run dev:worker
    environment:
      - IS_UNDER_DOCKER=true
    env_file:
      - .env
    restart: always
    depends_on:
      - hurado-postgres
    links:
      - hurado-postgres
    volumes:
      - ./:/app/
  hurado-postgres:
    container_name: hurado-postgres
    image: postgres:14-bullseye
    command: ["postgres", "-c", "log_statement=all"]
    restart: always
    env_file:
      - .env
    ports:
      - 5432:5432
    volumes:
      - ./volumes/postgresql:/var/lib/postgresql/data/
  hurado-azurite:
    container_name: hurado-azurite
    image: mcr.microsoft.com/azure-storage/azurite
    ports:
      - "10000"  # Blob service
    environment:
      - AZURITE_ACCOUNTS=hurado:password
    volumes:
      - ./volumes/azurite:/data
    command: "azurite-blob -l /data --blobHost 0.0.0.0 --blobPort 10000"
  hurado-redis:
    container_name: hurado-redis
    image: redis:7.4-bookworm
    ports:
      - "6379"  # Blob service
    volumes:
      - ./volumes/redis:/data
