version: '3.3'

services:
  hurado-postgres:
    container_name: hurado-postgres
    profiles:
      - backend
    image: postgres:14-bullseye
    restart: always
    env_file:
      - .env
    ports:
      - 5432:5432
    volumes:
      - ./web-server/database/postgres:/var/lib/postgres/data/
