version: '3'

services:
  be_boilerplate:
    command: /bin/sh -c "echo 'Running API on production!' && npm run build && npm start"
    ports:
      - '4000:4000'
    env_file:
      - ./config/stage.env
