/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/auth/login': {
    post: {
      responses: {
        /** OK */
        200: unknown;
        /** Bad request */
        400: unknown;
      };
      requestBody: {
        content: {
          'application/json': components['schemas']['Auth_Login'];
        };
      };
    };
  };
  '/auth/register': {
    post: {
      responses: {
        /** OK */
        200: unknown;
        /** Bad request */
        400: unknown;
      };
      requestBody: {
        content: {
          'application/json': components['schemas']['Auth_Register'];
        };
      };
    };
  };
  '/users/{id}': {
    get: {
      parameters: {
        path: {
          id: string;
        };
      };
      responses: {
        /** OK */
        200: unknown;
        /** Bad request */
        400: unknown;
      };
    };
    patch: {
      parameters: {
        path: {
          id: string;
        };
      };
      responses: {
        /** OK */
        200: {
          content: {
            'application/json': components['schemas']['User_Read'];
          };
        };
        /** Bad request */
        400: unknown;
      };
      requestBody: {
        content: {
          'application/json': components['schemas']['User_Patch'];
        };
      };
    };
    parameters: {
      path: {
        id: string;
      };
    };
  };
  '/tasks': {
    get: {
      responses: {
        /** OK */
        200: {
          content: {
            'application/json': components['schemas']['Task_List'][];
          };
        };
      };
    };
  };
  '/tasks/{id}': {
    get: {
      parameters: {
        path: {
          id: string;
        };
      };
      responses: {
        /** OK */
        200: {
          content: {
            'application/json': components['schemas']['Task_Read'];
          };
        };
      };
    };
    parameters: {
      path: {
        id: string;
      };
    };
  };
  '/tasks/find/{idOrSlug}': {
    get: {
      parameters: {
        path: {
          /** A task id or taks slug */
          idOrSlug: string;
        };
      };
      responses: {
        /** OK */
        200: {
          content: {
            'application/json': components['schemas']['Task_Read'];
          };
        };
      };
    };
    parameters: {
      path: {
        /** A task id or taks slug */
        idOrSlug: string;
      };
    };
  };
  '/judge/tasks': {
    post: {
      responses: {
        /** OK */
        200: {
          content: {
            'application/json': components['schemas']['Task_List'][];
          };
        };
      };
      requestBody: {
        content: {
          'application/json': components['schemas']['Task_Setter'];
        };
      };
    };
  };
  '/judge/tasks/{id}': {
    get: {
      parameters: {
        path: {
          id: string;
        };
      };
      responses: {
        /** OK */
        200: {
          content: {
            'application/json': components['schemas']['Task_Setter'];
          };
        };
      };
    };
    patch: {
      parameters: {
        path: {
          id: string;
        };
      };
      responses: {
        /** OK */
        200: {
          content: {
            'application/json': components['schemas']['Task_Setter'];
          };
        };
        /** Bad request */
        400: unknown;
      };
      requestBody: {
        content: {
          'application/json': components['schemas']['Task_Setter'];
        };
      };
    };
    parameters: {
      path: {
        id: string;
      };
    };
  };
  '/files/upload': {
    post: {
      responses: {
        /** OK */
        200: {
          content: {
            'application/json': components['schemas']['File_Read'];
          };
        };
        /** Bad request */
        400: unknown;
      };
      requestBody: {
        content: {
          'application/json': components['schemas']['File_Create'];
        };
      };
    };
  };
  '/scripts/create': {
    post: {
      responses: {
        /** OK */
        200: unknown;
        /** Bad request */
        400: unknown;
      };
      requestBody: {
        content: {
          'application/json': components['schemas']['Script'];
        };
      };
    };
  };
}

export interface components {
  schemas: {
    Auth_Login: {
      email: string;
      password: string;
    };
    Auth_Register: {
      email: string;
      username: string;
      password: string;
    };
    User_Patch: {
      id: string;
      email: string;
      username: string;
      password?: string;
      school?: string;
      firstName?: string;
      lastName?: string;
      country?: string;
    };
    User_Read: {
      id: string;
      email: string;
      username: string;
    };
    File_Read: {
      id: string;
      fileURL: string;
      name: string;
    };
    File_Create: {
      fileURL: string;
      name: string;
    };
    Script: {
      file: components['schemas']['File_Read'];
      languageCode: string;
      runtimeArgs: string;
    };
    Task_List: {
      id: string;
      title: string;
      slug: string;
    };
    Task_Read: {
      id: string;
      title: string;
      slug: string;
      description?: string;
      allowedLanguages: string;
      taskType: string;
      scoreMax: number;
      timeLimit: number;
      memoryLimit: number;
      compileTimeLimit: number;
      compileMemoryLimit?: number;
      submissionSizeLimit: number;
      validatorId?: number;
      isPublicInArchive: boolean;
      language: string;
    } & {
      statement: unknown;
    };
    Task_Setter: components['schemas']['Task_Read'] & {
      checkerId: number;
      validatorId?: number;
    };
  };
}

export interface operations {}

export interface external {}
