#!/bin/bash

command=$1

if [ "$command" = "status" ]; then
    pm2 status
elif [ "$command" = "prod:start" ]; then
    npm run build
    pm2 start -n hurado:prod npx -- next start -- -p 10001
elif [ "$command" = "prod:stop" ]; then
    pm2 stop hurado:prod
    pm2 delete hurado:prod
elif [ "$command" = "prod:restart" ]; then
    pm2 stop hurado:prod
    pm2 delete hurado:prod

    npm run build

    pm2 start -n hurado:prod npx -- next start -- -p 10001
elif [ "$command" = "prod:logs" ]; then
    pm2 logs hurado:prod --lines 100
else 
    echo "Usage:"
    echo "  ./<path>/dev [command]"
    echo ""
    echo "Commands:"
    echo "  prod:start      start the production server"
    echo "  prod:stop       stop the production server"
    echo "  prod:restart    restart the production server"
    echo "  prod:logs       show the logs of the production server"
    echo ""
    echo "  status          show the status of all running pm2 processes"
fi
