swagger: '2.0'
info:
  version: 1.0.0
  title: REST API
  description: ''
host: localhost:3000
basePath: '/'
schemes:
  - http
paths:
  /auth/login:
    post:
      parameters:
        - in: body
          name: user
          schema:
            type: object
            required:
              - email
              - password
            properties:
              email:
                type: string
              password:
                type: string
      responses:
        200:
          description: OK
        400:
          description: Bad request
        404:
          description: Not found
  /auth/register:
    post:
      parameters:
        - in: body
          name: user
          schema:
            type: object
            required:
              - email
              - username
              - password
            properties:
              email:
                type: string
              username:
                type: string
              password:
                type: string
      responses:
        200:
          description: OK
        400:
          description: Bad request
        404:
          description: Not found
  /files/upload:
    post:
      responses:
        200:
          description: OK
        400:
          description: Bad request
        404:
          description: Not found
  /scripts/create:
    post:
      parameters:
        - in: body
          name: script
          schema:
            $ref: '#/definitions/Script'
      responses:
        200:
          description: OK
        400:
          description: Bad request
        404:
          description: Not found
  /tasks:
    get:
      responses:
        200:
          description: OK
        400:
          description: Bad request
  /tasks/create:
    post:
      parameters:
        - in: body
          name: task
          schema:
            $ref: '#/definitions/Task'
      responses:
        200:
          description: OK
        400:
          description: Bad request
        404:
          description: Not found
  /tasks/{id([0-9]+)}:
    patch:
      parameters:
        - in: path
          name: id([0-9]+)
          type: integer
          required: true
        - in: body
          name: task
          schema:
            type: object
            properties:
              title:
                type: string
              slug:
                type: string
              description:
                type: string
              allowedLanguages:
                type: string
              taskType:
                type: string
              scoreMax:
                type: integer
              checkerId:
                type: integer
              timeLimit:
                type: number
              memoryLimit:
                type: integer
              compileTimeLimit:
                type: number
              compileMemoryLimit:
                type: integer
              submissionSizeLimit:
                type: integer
              validatorId:
                type: integer
              isPublicInArchive:
                type: boolean
              language:
                type: string
      responses:
        200:
          description: OK
        400:
          description: Bad request
        404:
          description: Not found
    get:
      parameters:
        - in: path
          name: id([0-9]+)
          type: integer
          required: true
      responses:
        200:
          description: OK
        400:
          description: Bad request
        404:
          description: Not found
  /tasks/show/{id([0-9]+)}:
    get:
      parameters:
        - in: path
          name: id([0-9]+)
          type: integer
          required: true
      responses:
        200:
          description: OK
        400:
          description: Bad request
        404:
          description: Not found
  /tasks/view/{idOrSlug([0-9A-Za-z]+)}:
    get:
      parameters:
        - in: path
          name: idOrSlug([0-9A-Za-z]+)
          type: string
          required: true
      responses:
        200:
          description: OK
        400:
          description: Bad request
        404:
          description: Not found
  /users/{id([0-9]+)}:
    get:
      parameters:
        - in: path
          name: id([0-9]+)
          type: integer
          required: true
      responses:
        200:
          description: OK
        400:
          description: Bad request
        404:
          description: Not found
    patch:
      parameters:
        - in: path
          name: id([0-9]+)
          type: integer
          required: true
        - in: body
          name: user
          schema:
            type: object
            properties:
              email:
                type: string
              username:
                type: string
              password:
                type: string
              passwordConfirm:
                type: string
              school:
                type: string
              firstName:
                type: string
              lastName:
                type: string
              country:
                type: string
      responses:
        200:
          description: OK
        400:
          description: Bad request
        404:
          description: Not found
    delete:
      parameters:
        - in: path
          name: id([0-9]+)
          type: integer
          required: true
      responses:
        200:
          description: OK
        400:
          description: Bad request
        404:
          description: Not found
definitions:
  File:
    type: object
    required:
      - fileURL
      - name
    properties:
      fileURL:
        type: string
      name:
        type: string
  Script:
    type: object
    required:
      - file
      - languageCode
      - runtimeArgs
    properties:
      file:
        $ref: '#/definitions/File'
      languageCode:
        type: string
      runtimeArgs:
        type: string
  Task:
    type: object
    required:
      - title
      - slug
      - statement
      - allowedLanguages
      - taskType
      - scoreMax
      - checkerId
      - timeLimit
      - memoryLimit
      - compileTimeLimit
      - submissionSizeLimit
      - isPublicInArchive
      - language
    properties:
      title:
        type: string
      slug:
        type: string
      description:
        type: string
      allowedLanguages:
        type: string
      taskType:
        type: string
      scoreMax:
        type: integer
      checkerId:
        type: integer
      timeLimit:
        type: number
      memoryLimit:
        type: integer
      compileTimeLimit:
        type: number
      compileMemoryLimit:
        type: integer
      submissionSizeLimit:
        type: integer
      validatorId:
        type: integer
      isPublicInArchive:
        type: boolean
      language:
        type: string
